# Generated by Django 4.0.5 on 2022-07-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postcod',
            new_name='postcode',
        ),
    ]
